steps:
- script: |
    dotnet build --verbosity minimal /p:ContinuousIntegrationBuild=true;VersionSuffix=ci-$(Build.BuildNumber)
    dotnet test --logger trx --no-build --verbosity minimal
    dotnet pack --output $(Build.ArtifactStagingDirectory) --no-build --verbosity minimal
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

trigger:
  paths:
    exclude:
    - README.md