steps:
- task: DotNetCoreCLI@2
    command: build
    buildProperties: ContinuousIntegrationBuild=true
- task: DotNetCoreCLI@2
    command: test
    nobuild: true
- task: DotNetCoreCLI@2
    command: pack
    nobuild: true
    packagesToPack: '.dotnetproj'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

trigger:
  paths:
    exclude:
    - README.md