steps:
- script: |
    dotnet build /p:ContinuousIntegrationBuild=true;VersionSuffix=ci-$(Build.BuildNumber)
- script: |
    dotnet test --logger trx --no-build
- script: |
    dotnet pack --output $(Build.ArtifactStagingDirectory) --no-build
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

trigger:
  paths:
    exclude:
    - README.md