steps:
- script: |
    dotnet build --version-suffix ci-$(Build.BuildNumber) /p:ContinuousIntegrationBuild=true
- script: |
    dotnet test --logger trx --no-build
- script: |
    dotnet pack --version-suffix ci-$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory) --no-build
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

trigger:
  paths:
    exclude:
    - README.md