steps:
- task: DotNetCoreCLI@2
  displayName: 'solution.build'
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: 'solution.test'
  inputs:
    command: 'test'
    nobuild: 'true'
- task: PublishTestResults@2
  displayName: 'solution.test.publish'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: DotNetCoreCLI@2
  displayName: 'solution.pack'
  inputs:
    command: 'pack'
    nobuild: 'true'