steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'build'
    arguments: '$(Build.SourcesDirectory)/global.proj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'test'
    arguments: '$(Build.SourcesDirectory)/global.proj --logger trx --results-directory $(Agent.TempDirectory) --no-build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: '$(Build.SourcesDirectory)/global.proj --output $(Build.ArtifactStagingDirectory) --no-build'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    searchFolder: '$(Agent.TempDirectory)'
- task: PublishBuildArtifacts@1