# © Alexander Kozlenko. Licensed under the MIT License.

variables:
  Project.FilePath: '$(Build.SourcesDirectory)/global.proj'
  Project.Configuration: 'Release'
stages:
- stage: Build
  jobs:
  - job: Packages
    displayName: 'Packages'
    steps:
    - task: PowerShell@2
      inputs:
        pwsh: true
        targetType: inline
        script: |
            Write-Host ('##vso[task.setvariable variable=DotNetCoreSdkVersion;]' + (Get-Content -Raw '$(Build.SourcesDirectory)/global.json' | ConvertFrom-Json).'sdk'.'version')
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '$(DotNetCoreSdkVersion)'
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: build
        arguments: '$(Project.FilePath) --configuration $(Project.Configuration) -property:ContinuousIntegrationBuild=true'
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: pack
        arguments: '$(Project.FilePath) --configuration $(Project.Configuration) --no-build --include-symbols --output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'artifact'
        targetPath: '$(Build.ArtifactStagingDirectory)'
- stage: Test
  condition: succeeded()
  jobs:
  - job: PackagesAndCoverage
    displayName: 'Packages and Coverage'
    steps:
    - task: PowerShell@2
      inputs:
        pwsh: true
        targetType: inline
        script: |
            Write-Host ('##vso[task.setvariable variable=DotNetCoreSdkVersion;]' + (Get-Content -Raw '$(Build.SourcesDirectory)/global.json' | ConvertFrom-Json).'sdk'.'version')
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DotNetCoreSdkVersion)
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: test
        arguments: '$(Project.FilePath) --configuration $(Project.Configuration) -property:EnableCodeCoverage=false --logger trx --results-directory $(Agent.TempDirectory)'
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
        searchFolder: '$(Agent.TempDirectory)'
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: test
        arguments: '$(Project.FilePath) --configuration $(Project.Configuration) -property:EnableCodeCoverageReport=false'
- stage: Deploy
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: MyGet
    displayName: 'MyGet'
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'artifact'
        targetPath: '$(Build.ArtifactStagingDirectory)'
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '5.0.0'
    - task: NuGetCommand@2
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: MyGet
