pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: dotnet build
  displayName: 'dotnet build'
- script: dotnet test --no-build
  displayName: 'dotnet test'
- script: dotnet pack --no-build
  displayName: 'dotnet pack'