name: "AppInspector"
on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '.github/**/*.md'
  pull_request:
    branches:
    - 'main'
    paths-ignore:
    - '.github/**/*.md'
jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
    - name: inspect
      uses: microsoft/ApplicationInspector-Action@v1
      with:
        arguments: -t
